export const characterConst = {
    SET_CHARACTERS: 'SET_CHARACTERS',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    SET_TOTAL_CHARCTERS_COUNT: 'SET_TOTAL_CHARCTERS_COUNT',
    TOOGLE_IS_FETCHING: 'TOOGLE_IS_FETCHING'
};

export const locationsConstants = {
    SET_LOCATIONS: 'SET_LOCATIONS',
    ET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    SET_TOTAL_LOCATIONS_COUNT: 'SET_TOTAL_LOCATIONS_COUNT'
};

export const EpisodesConstants = {
    SET_EPISODES: 'SET_EPISODES',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    SET_TOTAL_EPISODES_COUNT: 'SET_TOTAL_EPISODES_COUNT'
};